import { motion } from "framer-motion"
import { useState } from "react"

const faqs = [

  {
    question: "How does Velora AI work?",
    answer:
      "Velora uses advanced AI workflows to generate modern startup-quality websites instantly.",
  },

  {
    question: "Can I customize templates?",
    answer:
      "Yes. Every generated design can be fully customized with your own branding, content, and layout.",
  },

  {
    question: "Is Velora beginner friendly?",
    answer:
      "Absolutely. Velora is designed for creators, startups, developers, and beginners alike.",
  },

  {
    question: "Does Velora support responsive design?",
    answer:
      "Yes. Every website generated by Velora is optimized for desktop, tablet, and mobile devices.",
  },

]

export default function FAQ() {

  const [active, setActive] = useState(null)

  return (

    <section className="relative py-32 px-6 overflow-hidden">

      {/* Glow */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-blue-500/5 to-transparent"></div>

      <div className="relative z-10 max-w-5xl mx-auto">

        {/* Heading */}
        <motion.div

          initial={{
            opacity: 0,
            y: 40,
          }}

          whileInView={{
            opacity: 1,
            y: 0,
          }}

          viewport={{
            once: true,
          }}

          transition={{
            duration: 0.7,
          }}

          className="text-center mb-20"
        >

          <p className="text-blue-400 uppercase tracking-[0.3em] text-sm mb-4">

            FAQ

          </p>

          <h2 className="text-5xl md:text-6xl font-semibold leading-tight">

            Frequently asked
            <br />

            questions.

          </h2>

        </motion.div>

        {/* FAQ Items */}
        <div className="space-y-6">

          {faqs.map((faq, index) => (

            <motion.div
              key={index}

              initial={{
                opacity: 0,
                y: 30,
              }}

              whileInView={{
                opacity: 1,
                y: 0,
              }}

              viewport={{
                once: true,
              }}

              transition={{
                duration: 0.5,
                delay: index * 0.1,
              }}

              className="rounded-[28px] border border-white/10 bg-white/[0.04] backdrop-blur-2xl overflow-hidden"
            >

              <button

                onClick={() =>
                  setActive(active === index ? null : index)
                }

                className="w-full flex items-center justify-between px-8 py-6 text-left"
              >

                <h3 className="text-xl font-medium">

                  {faq.question}

                </h3>

                <span className="text-3xl text-blue-400">

                  {active === index ? "−" : "+"}

                </span>

              </button>

              <motion.div

                initial={false}

                animate={{
                  height: active === index ? "auto" : 0,
                  opacity: active === index ? 1 : 0,
                }}

                transition={{
                  duration: 0.3,
                }}

                className="overflow-hidden"
              >

                <p className="px-8 pb-6 text-gray-400 leading-relaxed">

                  {faq.answer}

                </p>

              </motion.div>

            </motion.div>

          ))}

        </div>

      </div>

    </section>

  )

}